{% set name = "aiohttp-retry" %}
{% set version = "2.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/aiohttp_retry-{{ version }}.tar.gz
  sha256: 91c0cd902cd0bdc63c3f5738cd574b42961f9364d10dbba2fbbdcdf283814543

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - aiohttp
    - python >=3.6

test:
  imports:
    - aiohttp_retry
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/inyutin/aiohttp_retry
  summary: Simple retry client for aiohttp
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - isidentical
    - efiop
